name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight UTC
  workflow_dispatch:      # allows manual run

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Ganesh-Tanpure
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution graph"
          add: "./output"
